# Generated by Django 5.0.1 on 2024-03-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cod_producto',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
