# Generated by Django 5.0.1 on 2024-03-19 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={},
        ),
    ]
