# Generated by Django 5.0.2 on 2024-02-28 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_ciudad_ciudad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='ciudad',
            new_name='idciudad',
        ),
    ]
