# Generated by Django 5.0.2 on 2024-02-28 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_rename_ciudad_direccion_idciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='idcontacto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ventas.contacto'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='iddireccion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ventas.direccion'),
        ),
    ]
