# Generated by Django 5.0.2 on 2024-02-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_persona_idcontacto_alter_persona_iddireccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioid',
            name='usuario',
            field=models.CharField(max_length=45),
        ),
    ]
