# Generated by Django 5.0.2 on 2024-02-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_usuarioid_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioid',
            name='contrasena',
            field=models.CharField(default='password', max_length=25),
            preserve_default=False,
        ),
    ]
