# Generated by Django 5.0.2 on 2024-02-29 03:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_usuarioid_contrasena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='idtipomovimiento_movimeinto',
            new_name='idtipo_movimiento',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='idubicacioninventarioinv',
            new_name='idubicacion_inventario',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='fechai_nventario',
        ),
        migrations.AddField(
            model_name='inventario',
            name='fecha_inventario',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
