# Generated by Django 5.0.2 on 2024-03-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_alter_pqr_fecha_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pqr',
            name='fechac_cierre',
        ),
        migrations.AddField(
            model_name='pqr',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
    ]
