# Generated by Django 5.0.2 on 2024-03-05 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_remove_pqr_fechac_cierre_pqr_fecha_cierre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedadproducto',
            name='fecha_novedad',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
